"""
Infrastructure Project Templates.

Generates project configuration files:
- pyproject.toml
- .env.example
- .gitignore
- README.md
- fcube.py script
"""


def generate_pyproject_toml(project_name: str, with_celery: bool = True) -> str:
    """Generate pyproject.toml"""
    celery_deps = ""
    if with_celery:
        celery_deps = '''
    "celery>=5.4.0",
    "redis>=5.0.1",
    "flower>=2.0.1",'''

    return f'''[project]
name = "{project_name}"
version = "0.1.0"
description = "FastAPI application generated by FCube CLI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.0",
    "asyncpg>=0.30.0",
    "fastapi>=0.115.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.0",
    "uvicorn[standard]>=0.30.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt>=4.0.1,<5.0.0",{celery_deps}
    "typer>=0.12.0",
    "rich>=13.0.0",
]
'''


def generate_env_example(project_name: str, with_celery: bool = True) -> str:
    """Generate .env.example"""
    celery_env = ""
    if with_celery:
        celery_env = '''
# ==================== Celery Configuration ====================
CELERY_BROKER_URL=
CELERY_RESULT_BACKEND=

# ==================== Flower Configuration ====================
FLOWER_PORT=5555
FLOWER_USERNAME=admin
FLOWER_PASSWORD=change_me_flower_password
'''

    return f'''# ==================== Environment Configuration ====================
# Copy this file to .env and update with your actual values

# ==================== Application Settings ====================
APP_NAME={project_name.replace("_", " ").title()}
APP_VERSION=0.1.0
ENVIRONMENT=development
DEBUG=true

# ==================== API Settings ====================
API_V1_PREFIX=/api/v1
API_PORT=8000
HOST=0.0.0.0

# ==================== Database Configuration ====================
POSTGRES_USER=fastapi_user
POSTGRES_PASSWORD=change_me_secure_password
POSTGRES_DB={project_name}_db
POSTGRES_HOST=postgres  # Use 'postgres' for Docker, 'localhost' for local
POSTGRES_PORT=5432

# Database Pool Settings
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=10
DB_POOL_TIMEOUT=30
DB_ECHO=false

# ==================== Security Settings ====================
# IMPORTANT: Generate strong keys using: python -c "import secrets; print(secrets.token_urlsafe(32))"
SECRET_KEY=your-secret-key-must-be-at-least-32-characters-long
JWT_SECRET_KEY=your-jwt-secret-must-be-at-least-32-characters-long

# ==================== CORS Settings ====================
CORS_ORIGINS=http://localhost:3000,http://localhost:8000

# ==================== Logging ====================
LOG_LEVEL=INFO

# ==================== Redis Configuration ====================
REDIS_HOST=redis  # Use 'redis' for Docker, 'localhost' for local
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=
{celery_env}'''


def generate_gitignore() -> str:
    """Generate .gitignore"""
    return '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.venv/
venv/
ENV/
env/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log

# Database
*.db
*.sqlite3

# Celery
celerybeat-schedule
celerybeat-schedule.*

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/

# Mypy
.mypy_cache/

# Jupyter
.ipynb_checkpoints/

# OS
.DS_Store
Thumbs.db

# Project specific
migrations/versions/*.pyc
'''


def generate_project_readme(
    project_name: str,
    project_pascal: str,
    with_celery: bool = True,
    with_docker: bool = True
) -> str:
    """Generate README.md"""
    docker_section = ""
    if with_docker:
        docker_section = '''
## 🐳 Docker

### Start with Docker Compose

```bash
# Start all services
docker-compose up -d

# View logs
docker-compose logs -f api

# Stop services
docker-compose down
```

### Services

| Service | Port | Description |
|---------|------|-------------|
| API | 8000 | FastAPI application |
| PostgreSQL | 5432 | Database |
| Redis | 6379 | Cache/Celery broker |'''

        if with_celery:
            docker_section += '''
| Celery Worker | - | Background tasks |
| Flower | 5555 | Task monitoring |'''

    celery_section = ""
    if with_celery:
        celery_section = '''
## ⚡ Background Tasks

This project uses Celery for background task processing.

### Start Celery Worker (without Docker)

```bash
celery -A app.core.celery_app:celery_app worker --loglevel=info
```

### Flower Monitoring

Access Flower at: http://localhost:5555
'''

    return f'''# {project_pascal}

> FastAPI application generated by FCube CLI

## 🚀 Quick Start

### 1. Setup Environment

```bash
cp .env.example .env
# Edit .env with your configuration
```

### 2. Install Dependencies

```bash
pip install uv
uv pip install -r pyproject.toml
```

### 3. Start Services

```bash
# With Docker (recommended)
docker-compose up -d postgres redis

# Or run PostgreSQL and Redis locally
```

### 4. Run Migrations

```bash
alembic revision --autogenerate -m "Initial migration"
alembic upgrade head
```

### 5. Start Application

```bash
# Development
uvicorn app.core.main:app --reload

# With Docker
docker-compose up -d
```

### 6. Access API

- **API Docs**: http://localhost:8000/docs
- **ReDoc**: http://localhost:8000/redoc
- **Health Check**: http://localhost:8000/health
{docker_section}
{celery_section}
## 📁 Project Structure

```
{project_name}/
├── app/
│   ├── apis/           # API routers
│   │   └── v1.py       # Version 1 routes
│   ├── core/           # Core infrastructure
│   │   ├── database.py # Database setup
│   │   ├── settings.py # Configuration
│   │   ├── crud.py     # Base CRUD operations
│   │   └── main.py     # FastAPI app
│   └── user/           # User module
│       ├── models.py   # User model
│       ├── schemas.py  # Pydantic schemas
│       ├── crud.py     # User CRUD
│       └── auth_management/
├── migrations/         # Alembic migrations
├── docker/            # Docker configuration
├── docker-compose.yml
└── fcube.py           # Module generator
```

## 🛠️ Creating New Modules

Use FCube CLI to create new modules:

```bash
# Create a new module
python fcube.py startmodule Product

# List all modules
python fcube.py listmodules
```

## 📝 API Endpoints

### Authentication

| Method | Endpoint | Description |
|--------|----------|-------------|
| POST | `/api/v1/auth/register` | Register new user |
| POST | `/api/v1/auth/login` | Login user |
| POST | `/api/v1/auth/refresh` | Refresh token |
| GET | `/api/v1/auth/me` | Get current user |

---

Generated by [FCube CLI](https://github.com/your-repo/fcube)
'''


def generate_fcube_script() -> str:
    """Generate fcube.py script for the new project."""
    return '''#!/usr/bin/env python
"""
FCube CLI - Module Generator

Usage:
    python fcube.py startmodule <ModuleName>
    python fcube.py listmodules
"""

# Note: To use FCube CLI in this project, you need to have
# the fcube package installed or available in your path.
#
# For now, you can copy the fcube/ directory from the parent project
# or install it as a package.

try:
    from fcube.cli import app
    
    if __name__ == "__main__":
        app()
except ImportError:
    print("FCube CLI not found. Please install it or copy the fcube/ directory.")
    print("For module generation, use the FCube CLI from your main project.")
'''
