"""
Config template for deploy-vps plugin.
Generates the config.env.example file - the single source of truth.
"""


def generate_config_env_example() -> str:
    """Generate config.env.example file content."""
    return '''# ==================== Deploy-VPS Configuration ====================
# Single source of truth for deployment configuration
# Copy this file to config.env and customize for your project
# All templates will be generated from these values

# ==================== Project Identity ====================
PROJECT_NAME=myproject
BASE_DOMAIN=example.com

# ==================== Domain Configuration ====================
# Subdomains will be combined with BASE_DOMAIN automatically
# Example: api.example.com, flower.example.com
API_SUBDOMAIN=api
FLOWER_SUBDOMAIN=flower

# For staging testing, you might use:
# API_SUBDOMAIN=api-staging
# FLOWER_SUBDOMAIN=flower-staging

# ==================== Contact Email ====================
# Used for SSL certificate notifications from Let's Encrypt
ACME_EMAIL=admin@example.com

# ==================== Production Configuration ====================
# These values are used when deploying with --env production

# API Workers (gunicorn workers for FastAPI)
PRODUCTION_API_WORKERS=4

# Celery Workers (background task concurrency)
PRODUCTION_CELERY_WORKERS=4

# PostgreSQL Database (Managed Database recommended for production)
PRODUCTION_POSTGRES_HOST=your-db-host.db.example.com
PRODUCTION_POSTGRES_PORT=25060
PRODUCTION_POSTGRES_DB=defaultdb
PRODUCTION_POSTGRES_USER=dbadmin
PRODUCTION_POSTGRES_PASSWORD=CHANGE_THIS_YOUR_DB_PASSWORD

# Database SSL Mode (require for managed databases)
PRODUCTION_DB_SSL_MODE=require

# ==================== Staging Configuration ====================
# These values are used when deploying with --env staging
# Optimized for minimal staging environment

# API Workers (1 worker for minimal staging environment)
STAGING_API_WORKERS=1

# Celery Workers (1 worker with concurrency 1 for minimal staging)
STAGING_CELERY_WORKERS=1

# PostgreSQL Database (Containerized - runs in Docker)
STAGING_POSTGRES_HOST=postgres
STAGING_POSTGRES_PORT=5432
STAGING_POSTGRES_DB=staging_db
STAGING_POSTGRES_USER=staging_user
STAGING_POSTGRES_PASSWORD=CHANGE_THIS_STAGING_DB_PASSWORD

# Database SSL Mode (disable for containerized database)
STAGING_DB_SSL_MODE=disable

# ==================== Flower Monitoring Credentials ====================
# These are used for both production and staging
# You can override per-environment if needed
FLOWER_USERNAME=admin
FLOWER_PASSWORD=CHANGE_THIS_STRONG_FLOWER_PASSWORD

# ==================== Auto-Generated Values ====================
# The following values are automatically derived by setup.sh
# You don't need to set these - they're shown here for reference:
#
# API_DOMAIN = ${API_SUBDOMAIN}.${BASE_DOMAIN}
#   Example: api.example.com
#
# FLOWER_DOMAIN = ${FLOWER_SUBDOMAIN}.${BASE_DOMAIN}
#   Example: flower.example.com
#
# PROJECT_PREFIX = sanitized version of PROJECT_NAME
#   Example: myproject (used for Docker container names)
#
# CONTAINER_PREFIX = ${PROJECT_PREFIX}_ or ${PROJECT_PREFIX}_staging_
#   Example: myproject_nginx, myproject_api
#
# NETWORK_PREFIX = ${PROJECT_PREFIX}_network or ${PROJECT_PREFIX}_staging_network
#   Example: myproject_network
#
# NETWORK_SUBNET = 172.20.0.0/16 (production) or 172.21.0.0/16 (staging)
#
# TRUSTED_HOSTS = localhost,127.0.0.1,${API_DOMAIN},${BASE_DOMAIN},*.${BASE_DOMAIN}
#   Example: localhost,127.0.0.1,api.example.com,example.com,*.example.com
#
# CORS_ORIGINS = http://localhost:3000,https://${BASE_DOMAIN},https://www.${BASE_DOMAIN},https://app.${BASE_DOMAIN}
#   Example: http://localhost:3000,https://example.com,https://www.example.com,https://app.example.com

# ==================== Security Secrets ====================
# These will be auto-generated by setup.sh using openssl
# You can also manually generate them with: openssl rand -hex 32
#
# SECRET_KEY = (auto-generated 64-character hex string)
# JWT_SECRET_KEY = (auto-generated 64-character hex string)
# REDIS_PASSWORD = (auto-generated 32-character hex string)

# ==================== Usage ====================
# 1. Copy this file: cp config.env.example config.env
# 2. Edit config.env with your actual values
# 3. Run: ./scripts/setup.sh
#
# The setup.sh script will:
#   - Validate your configuration
#   - Generate secure secrets automatically
#   - Create .env.production and .env.staging from templates
#   - Generate docker-compose files
#   - Generate nginx configurations
#   - Generate redis configurations
#
# After initialization, you can customize the generated .env files:
#   - Edit .env.production for production-specific API keys
#   - Edit .env.staging for staging-specific settings

# ==================== Quick Start Example ====================
# PROJECT_NAME=myhotel
# BASE_DOMAIN=myhotel.com
# API_SUBDOMAIN=api
# FLOWER_SUBDOMAIN=flower
# ACME_EMAIL=admin@myhotel.com
#
# PRODUCTION_API_WORKERS=4
# PRODUCTION_CELERY_WORKERS=4
# PRODUCTION_POSTGRES_HOST=db-postgresql-nyc3-12345.example.com
# PRODUCTION_POSTGRES_PORT=25060
# PRODUCTION_POSTGRES_DB=myhotel_prod
# PRODUCTION_POSTGRES_USER=dbadmin
# PRODUCTION_POSTGRES_PASSWORD=<your-secure-password>
# PRODUCTION_DB_SSL_MODE=require
#
# STAGING_API_WORKERS=2
# STAGING_CELERY_WORKERS=2
# STAGING_POSTGRES_HOST=postgres
# STAGING_POSTGRES_PORT=5432
# STAGING_POSTGRES_DB=myhotel_staging
# STAGING_POSTGRES_USER=staging_user
# STAGING_POSTGRES_PASSWORD=<staging-db-password>
# STAGING_DB_SSL_MODE=disable
#
# FLOWER_USERNAME=admin
# FLOWER_PASSWORD=<strong-flower-password>
'''
