"""
Environment templates for deploy-vps plugin.
Generates .env template files for production and staging environments.
"""


def generate_production_env_template() -> str:
    """Generate production.env.template file content."""
    return '''# ==================== Environment ====================
ENVIRONMENT={{ENVIRONMENT}}
DEBUG={{DEBUG}}
PROJECT_NAME="{{PROJECT_NAME}}"
VERSION=1.0.0

# ==================== Application Settings ====================
APP_NAME="{{PROJECT_NAME}}"
APP_VERSION=1.0.0

# ==================== API Configuration ====================
API_V1_PREFIX=/api/v1
API_HOST=0.0.0.0
API_PORT=8000
API_WORKERS={{API_WORKERS}}
API_DOMAIN={{API_DOMAIN}}
API_URL=https://{{API_DOMAIN}}
HOST=0.0.0.0

# ==================== Security Keys ====================
# IMPORTANT: Auto-generated by setup.sh or manually generate with: openssl rand -hex 32
SECRET_KEY={{SECRET_KEY}}
JWT_SECRET_KEY={{JWT_SECRET_KEY}}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
JWT_TOKEN_URL=/api/v1/auth/login

# ==================== Password Settings ====================
PASSWORD_MIN_LENGTH=8
PASSWORD_HASH_ROUNDS=12

# ==================== Phone Verification Settings ====================
PHONE_VERIFICATION_CODE_LENGTH=6
PHONE_VERIFICATION_EXPIRE_MINUTES=10

# ==================== PostgreSQL Database ====================
POSTGRES_HOST={{POSTGRES_HOST}}
POSTGRES_PORT={{POSTGRES_PORT}}
POSTGRES_DB={{POSTGRES_DB}}
POSTGRES_USER={{POSTGRES_USER}}
POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
DATABASE_URL=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@{{POSTGRES_HOST}}:{{POSTGRES_PORT}}/{{POSTGRES_DB}}?sslmode={{DB_SSL_MODE}}
DB_POOL_SIZE=10
DB_MAX_OVERFLOW=5
DB_POOL_TIMEOUT=30
DB_ECHO=false
DB_SSL_MODE={{DB_SSL_MODE}}

# ==================== Redis (Containerized in Docker Compose) ====================
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD={{REDIS_PASSWORD}}
REDIS_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/0
REDIS_MAX_CONNECTIONS=20

# ==================== Celery Configuration ====================
CELERY_BROKER_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/0
CELERY_RESULT_BACKEND=redis://:{{REDIS_PASSWORD}}@redis:6379/1
CELERY_WORKER_PREFETCH_MULTIPLIER=4
CELERY_TASK_SOFT_TIME_LIMIT=300
CELERY_TASK_TIME_LIMIT=360

# Celery Worker Configuration
CELERY_WORKER_POOL=prefork
CELERY_WORKER_CONCURRENCY={{CELERY_WORKERS}}
CELERY_WORKER_MAX_TASKS_PER_CHILD=1000

# ==================== Flower Monitoring ====================
FLOWER_PORT=5555
FLOWER_DOMAIN={{FLOWER_DOMAIN}}
FLOWER_URL=https://{{FLOWER_DOMAIN}}
FLOWER_USERNAME={{FLOWER_USERNAME}}
FLOWER_PASSWORD={{FLOWER_PASSWORD}}
FLOWER_PERSISTENT=true

# ==================== Trusted Hosts (comma-separated) ====================
TRUSTED_HOSTS={{TRUSTED_HOSTS}}

# ==================== SMS Provider ====================
FAST2SMS_API_KEY=CHANGE_THIS_YOUR_FAST2SMS_API_KEY

# ==================== SSL Configuration ====================
ACME_EMAIL={{ACME_EMAIL}}

# ==================== Sentry Error Tracking ====================
SENTRY_DSN=CHANGE_THIS_YOUR_SENTRY_DSN
SENTRY_ENVIRONMENT=production
SENTRY_TRACES_SAMPLE_RATE=0.1
SENTRY_PROFILES_SAMPLE_RATE=0.1
SENTRY_RELEASE=
SENTRY_ENABLED=false

# ==================== Object Storage ====================
DO_SPACES_ENDPOINT_URL=https://blr1.digitaloceanspaces.com
DO_SPACES_ACCESS_KEY_ID=CHANGE_THIS_YOUR_SPACES_ACCESS_KEY
DO_SPACES_SECRET_ACCESS_KEY=CHANGE_THIS_YOUR_SPACES_SECRET_KEY
DO_SPACES_BUCKET_NAME={{PROJECT_PREFIX}}
DO_SPACES_REGION=blr1

# ==================== File Upload Settings ====================
MAX_FILE_SIZE_MB=10
ALLOWED_DOCUMENT_TYPES=image/jpeg,image/png,image/webp,application/pdf
DOCUMENT_URL_EXPIRY_HOURS=24
ENABLE_FILE_COMPRESSION=true
MAX_IMAGE_WIDTH=2048
MAX_IMAGE_HEIGHT=2048

# ==================== CORS Configuration ====================
CORS_ORIGINS={{CORS_ORIGINS}}
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
CORS_ALLOW_HEADERS=*

# ==================== Middleware Settings ====================
ENABLE_GZIP=true
GZIP_MINIMUM_SIZE=1000

# ==================== Logging ====================
LOG_LEVEL={{LOG_LEVEL}}
ENABLE_FILE_LOGGING=false

# ==================== Rate Limiting ====================
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60

# ==================== Timezone ====================
TZ=UTC

# ==================== Health Check Settings ====================
ENABLE_HEALTH_CHECK=true
HEALTH_CHECK_PATH=/health
READINESS_CHECK_PATH=/readiness

# ==================== Performance Optimization ====================
UVICORN_WORKERS={{API_WORKERS}}
UVICORN_LOG_LEVEL={{LOG_LEVEL}}
UVICORN_ACCESS_LOG=false

# ==================== API Documentation ====================
ENABLE_DOCS={{ENABLE_DOCS}}

# ==================== Backup Configuration ====================
BACKUP_RETENTION_DAYS=7
BACKUP_PATH=/app/backups
'''


def generate_staging_env_template() -> str:
    """Generate staging.env.template file content."""
    return '''# ==================== Environment ====================
ENVIRONMENT={{ENVIRONMENT}}
DEBUG={{DEBUG}}
PROJECT_NAME="{{PROJECT_NAME}}"
VERSION=1.0.0

# ==================== Application Settings ====================
APP_NAME="{{PROJECT_NAME}}"
APP_VERSION=1.0.0

# ==================== API Configuration ====================
API_V1_PREFIX=/api/v1
API_HOST=0.0.0.0
API_PORT=8000
API_WORKERS={{API_WORKERS}}
API_DOMAIN={{API_DOMAIN}}
API_URL=https://{{API_DOMAIN}}
HOST=0.0.0.0

# ==================== Security Keys ====================
# IMPORTANT: Auto-generated by setup.sh or manually generate with: openssl rand -hex 32
SECRET_KEY={{SECRET_KEY}}
JWT_SECRET_KEY={{JWT_SECRET_KEY}}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
JWT_TOKEN_URL=/api/v1/auth/login

# ==================== Password Settings ====================
PASSWORD_MIN_LENGTH=8
PASSWORD_HASH_ROUNDS=12

# ==================== Phone Verification Settings ====================
PHONE_VERIFICATION_CODE_LENGTH=6
PHONE_VERIFICATION_EXPIRE_MINUTES=10

# ==================== PostgreSQL Database (Containerized) ====================
POSTGRES_HOST={{POSTGRES_HOST}}
POSTGRES_PORT={{POSTGRES_PORT}}
POSTGRES_DB={{POSTGRES_DB}}
POSTGRES_USER={{POSTGRES_USER}}
POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
DATABASE_URL=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@{{POSTGRES_HOST}}:{{POSTGRES_PORT}}/{{POSTGRES_DB}}
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=3
DB_POOL_TIMEOUT=30
DB_ECHO=true
DB_SSL_MODE={{DB_SSL_MODE}}

# ==================== Redis (Containerized in Docker Compose) ====================
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD={{REDIS_PASSWORD}}
REDIS_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/0
REDIS_MAX_CONNECTIONS=10

# ==================== Celery Configuration ====================
CELERY_BROKER_URL=redis://:{{REDIS_PASSWORD}}@redis:6379/0
CELERY_RESULT_BACKEND=redis://:{{REDIS_PASSWORD}}@redis:6379/1
CELERY_WORKER_PREFETCH_MULTIPLIER=2
CELERY_TASK_SOFT_TIME_LIMIT=300
CELERY_TASK_TIME_LIMIT=360

# Celery Worker Configuration
CELERY_WORKER_POOL=prefork
CELERY_WORKER_CONCURRENCY={{CELERY_WORKERS}}
CELERY_WORKER_MAX_TASKS_PER_CHILD=500

# ==================== Flower Monitoring ====================
FLOWER_PORT=5555
FLOWER_DOMAIN={{FLOWER_DOMAIN}}
FLOWER_URL=https://{{FLOWER_DOMAIN}}
FLOWER_USERNAME={{FLOWER_USERNAME}}
FLOWER_PASSWORD={{FLOWER_PASSWORD}}
FLOWER_PERSISTENT=true

# ==================== Trusted Hosts (comma-separated) ====================
TRUSTED_HOSTS={{TRUSTED_HOSTS}}

# ==================== SMS Provider ====================
FAST2SMS_API_KEY=CHANGE_THIS_YOUR_FAST2SMS_API_KEY

# ==================== SSL Configuration ====================
ACME_EMAIL={{ACME_EMAIL}}

# ==================== Sentry Error Tracking ====================
SENTRY_DSN=
SENTRY_ENVIRONMENT=staging
SENTRY_TRACES_SAMPLE_RATE=0.5
SENTRY_PROFILES_SAMPLE_RATE=0.5
SENTRY_RELEASE=
SENTRY_ENABLED=false

# ==================== Object Storage ====================
DO_SPACES_ENDPOINT_URL=https://blr1.digitaloceanspaces.com
DO_SPACES_ACCESS_KEY_ID=CHANGE_THIS_YOUR_SPACES_ACCESS_KEY
DO_SPACES_SECRET_ACCESS_KEY=CHANGE_THIS_YOUR_SPACES_SECRET_KEY
DO_SPACES_BUCKET_NAME={{PROJECT_PREFIX}}-staging
DO_SPACES_REGION=blr1

# ==================== File Upload Settings ====================
MAX_FILE_SIZE_MB=10
ALLOWED_DOCUMENT_TYPES=image/jpeg,image/png,image/webp,application/pdf
DOCUMENT_URL_EXPIRY_HOURS=24
ENABLE_FILE_COMPRESSION=true
MAX_IMAGE_WIDTH=2048
MAX_IMAGE_HEIGHT=2048

# ==================== CORS Configuration ====================
CORS_ORIGINS={{CORS_ORIGINS}}
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
CORS_ALLOW_HEADERS=*

# ==================== Middleware Settings ====================
ENABLE_GZIP=true
GZIP_MINIMUM_SIZE=1000

# ==================== Logging ====================
LOG_LEVEL={{LOG_LEVEL}}
ENABLE_FILE_LOGGING=true

# ==================== Rate Limiting ====================
RATE_LIMIT_ENABLED=false
RATE_LIMIT_PER_MINUTE=120

# ==================== Timezone ====================
TZ=UTC

# ==================== Health Check Settings ====================
ENABLE_HEALTH_CHECK=true
HEALTH_CHECK_PATH=/health
READINESS_CHECK_PATH=/readiness

# ==================== Performance Optimization ====================
UVICORN_WORKERS={{API_WORKERS}}
UVICORN_LOG_LEVEL={{LOG_LEVEL}}
UVICORN_ACCESS_LOG=true

# ==================== API Documentation ====================
ENABLE_DOCS={{ENABLE_DOCS}}

# ==================== Backup Configuration ====================
BACKUP_RETENTION_DAYS=3
BACKUP_PATH=/app/backups
'''
