"""
Nginx configuration templates for deploy-vps plugin.
Generates nginx.conf, api.conf, and flower.conf templates.
"""


def generate_nginx_conf_template() -> str:
    """Generate nginx.conf.template file content."""
    return '''# Nginx Main Configuration
# Auto-generated by FCube CLI - Deploy VPS Plugin

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 2048;
    use epoll;
    multi_accept on;
}

http {
    # Basic Settings
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    charset utf-8;
    
    # Logging Format
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'rt=$request_time uct="$upstream_connect_time" '
                    'uht="$upstream_header_time" urt="$upstream_response_time"';
    
    access_log /var/log/nginx/access.log main;
    
    # Performance Optimizations
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;
    
    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_types text/plain text/css text/xml application/json application/javascript 
               application/xml application/rss+xml application/atom+xml image/svg+xml;
    
    # Rate Limiting Zones
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;
    limit_req_zone $binary_remote_addr zone=api_burst:10m rate=100r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
    
    # Rate Limiting Settings
    limit_req_status 429;
    limit_conn_status 429;
    
    # SSL Settings (Global)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    # Upstream Keepalive
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    
    # Include Site Configurations
    include /etc/nginx/sites-available/*.conf;
}
'''


def generate_api_conf_template() -> str:
    """Generate api.conf.template file content."""
    return '''# API Server Configuration - {{API_DOMAIN}}
# FastAPI Backend with SSL, Rate Limiting, and Security Headers

upstream api_backend {
    server api:8000 max_fails=3 fail_timeout=30s;
    keepalive 32;
}

# HTTP Server - Redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name {{API_DOMAIN}};

    # Let's Encrypt ACME Challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS Server - Main API
server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{API_DOMAIN}};

    # SSL Certificate Configuration
    ssl_certificate /etc/letsencrypt/live/{{API_DOMAIN}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{API_DOMAIN}}/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/{{API_DOMAIN}}/chain.pem;

    # SSL Optimization
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    # Rate Limiting
    # More lenient limits for modern SPA applications that make multiple requests
    limit_req zone=api_limit burst=30 nodelay;  # Allow 30 burst requests for page loads
    limit_req zone=api_burst burst=20 nodelay;  # Allow 20 burst per second
    limit_conn conn_limit 20;  # Allow 20 concurrent connections

    # Request Size Limits
    client_max_body_size 10M;
    client_body_buffer_size 128k;

    # Logging
    access_log /var/log/nginx/api-access.log main;
    error_log /var/log/nginx/api-error.log warn;

    # Health Check Endpoint (No Rate Limiting)
    location /health {
        proxy_pass http://api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        access_log off;
    }

    # Readiness Check Endpoint (No Rate Limiting)
    location /readiness {
        proxy_pass http://api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        access_log off;
    }

    # API Endpoints
    location / {
        # CORS is handled entirely by FastAPI using CORS_ORIGINS from .env
        # Nginx does NOT add CORS headers to avoid duplication

        # Proxy to FastAPI
        proxy_pass http://api_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header Connection "";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
        proxy_busy_buffers_size 8k;

        # Error Handling
        proxy_intercept_errors off;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
        proxy_next_upstream_timeout 30s;
    }

    # Static Files (if any served via nginx)
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Deny access to sensitive files (except .well-known for ACME)
    location ~ /\\.(?!well-known) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ /\\.env {
        deny all;
        access_log off;
        log_not_found off;
    }
}
'''


def generate_flower_conf_template() -> str:
    """Generate flower.conf.template file content."""
    return '''# Flower Server Configuration - {{FLOWER_DOMAIN}}
# Celery Monitoring Dashboard with SSL and Basic Auth

upstream flower_backend {
    server flower:5555 max_fails=3 fail_timeout=30s;
    keepalive 8;
}

# HTTP Server - Redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name {{FLOWER_DOMAIN}};

    # Let's Encrypt ACME Challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS Server - Flower Dashboard
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{FLOWER_DOMAIN}};

    # SSL Certificate Configuration
    ssl_certificate /etc/letsencrypt/live/{{FLOWER_DOMAIN}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{FLOWER_DOMAIN}}/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/{{FLOWER_DOMAIN}}/chain.pem;

    # SSL Optimization
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Rate Limiting (stricter for admin dashboard)
    limit_req zone=api_limit burst=10 nodelay;
    limit_conn conn_limit 5;

    # Request Size Limits
    client_max_body_size 1M;
    client_body_buffer_size 16k;

    # Logging
    access_log /var/log/nginx/flower-access.log main;
    error_log /var/log/nginx/flower-error.log warn;

    # Flower Dashboard
    location / {
        proxy_pass http://flower_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 300s;  # Longer for monitoring dashboard

        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 4 4k;
        proxy_busy_buffers_size 8k;
    }

    # Deny access to sensitive files
    location ~ /\\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
'''
